export const GET_ALL_POSTS = "GET_ALL_POSTS"
export const GET_ALL_TAGS = "GET_ALL_TAGS"
export const GET_ALL_COPYWRITERS = "GET_ALL_COPYWRITERS"

export const GET_ALL_POST = "GET_ALL_POST"
export const GET_ALL_TAG = "GET_ALL_TAG"
export const GET_ALL_COPYWRITER = "GET_ALL_COPYWRITER"
